# Generated by Django 3.1.1 on 2020-10-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='pages',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publish_company',
        ),
        migrations.RemoveField(
            model_name='books',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='books',
            name='state',
        ),
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
    ]
